name: CI with Continuous Validation

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run static analysis
        run: pylint src/

      - name: Run unit tests
        run: pytest --junitxml=test-results.xml

      - name: Run security scan
        uses: github/codeql-action/analyze@v3

