name: CI with Continuous Validation

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install pylint pytest

      - name: Run static analysis
        run: pylint python_app/

      - name: Run unit tests
        run: pytest python_app/tests/ --junitxml=test-results.xml
